INSERT INTO PERSON (ID,FIRSTNAME, LASTNAME) VALUES ('1','test1','test1');
INSERT INTO PERSON (ID,FIRSTNAME, LASTNAME) VALUES ('2','test2','test3');
INSERT INTO ADDRESS(ID,FK_PERSON,ADDLINE1,ADDLINE2,ZIPCODE) VALUES ('1','1','line1','line2','12345');
INSERT INTO ADDRESS(ID,FK_PERSON,ADDLINE1,ADDLINE2,ZIPCODE) VALUES ('2','1','line3','line4','12345');