CREATE TABLE PERSON
(
	ID VARCHAR(22) NOT NULL,
	FIRSTNAME VARCHAR2(50) NOT NULL,
  LASTNAME VARCHAR2(50) NOT NULL,
  PRIMARY KEY(ID)
);
CREATE TABLE ADDRESS
(
	ID VARCHAR(22) NOT NULL,
	FK_PERSON VARCHAR(22) NOT NULL,
	ADDLINE1 VARCHAR2(50) NOT NULL,
  ADDLINE2 VARCHAR2(50) NOT NULL,
  ZIPCODE VARCHAR(10) NOT NULL,
  PRIMARY KEY(ID),
  UNIQUE (ID,FK_PERSON),
  FOREIGN KEY (FK_PERSON) REFERENCES PERSON(ID)
);